# Generated by Django 4.1.3 on 2022-11-20 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='reaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.announce'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announce',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
