# Generated by Django 4.1.3 on 2022-11-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_announce_reaction_reaction_reaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='announce',
        ),
    ]
