# Generated by Django 4.0.3 on 2022-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_reaction_reaction_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
