# Generated by Django 4.0.3 on 2022-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_reaction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
